a = input("How many continents are there in the world?:")
print("Name any 3:")
print("")
b = tuple(map(str,input().split(",")))
c = list(b)
print(c)
d = input("How many countries are there in the world")
print("")
c.append(input("Also add the name of three countries"))
b = tuple(c)
print("")
print(f"There are {a} continents in the world")
print(f"There are {d} countries in the world")
print("These are the countries and continents you have listed",b)